"""Lowering: Cake-IR (Ascend flavor) -> inspectable AscendC source.

The paper's division of labor: the schedule states *what* happens; lowering
derives *how* — UB buffer offsets, bufferNum depths, HardEvent ids, flag
pairing, loop re-rolling from LoopMarkers — all computed from declarations
rather than written by the agent (paper 2.2).

Emitted code is structurally faithful AscendC (TPipe/TQue/TBuf, DataCopy,
SetFlag/WaitFlag, Matmul API, SyncAll). Compiling it requires a CANN
toolchain + Ascend hardware, which this Windows box lacks — locally the
simulator is the execution authority (README documents this honestly).

Multi-core programs lower per core into `if (GetBlockIdx() == k)` arms,
mirroring the per-core specialization that dispatcher portfolios use.
"""
from __future__ import annotations

from . import dtypes as dt
from .arch import Arch
from .ir import (
    Commit,
    Gm2Ub,
    HardBarrier,
    L0c2Ub,
    LoopMarker,
    Matmul,
    Program,
    Ub2Gm,
    VArgmin,
    VBcast,
    VBinary,
    VCast,
    VReduce,
    VTranspose,
    VUnary,
    Wait,
    shape_numel,
)

_ASCENDC_TYPE = {dt.BF16: "__bf16", dt.FP16: "__fp16", dt.FP32: "float",
                 dt.INT32: "int32_t"}

# HardEvent pairs are derived from role kinds (derived metadata, not authored)
_HARD_EVENT = {
    ("MTE2", "V"): "HardEvent::MTE2_V",
    ("V", "MTE2"): "HardEvent::V_MTE2",
    ("MTE3", "V"): "HardEvent::MTE3_V",
    ("V", "MTE3"): "HardEvent::V_MTE3",
    ("MTE2", "MTE3"): "HardEvent::MTE2_MTE3",
    ("MTE3", "MTE2"): "HardEvent::MTE3_MTE2",
    ("CUBE", "V"): "HardEvent::M_V",
    ("V", "CUBE"): "HardEvent::V_M",
    ("CUBE", "MTE2"): "HardEvent::M_MTE2",
    ("MTE2", "CUBE"): "HardEvent::MTE2_M",
    ("CUBE", "MTE3"): "HardEvent::M_MTE3",
    ("MTE3", "CUBE"): "HardEvent::MTE3_M",
}


class AscendCCodeGen:
    def __init__(self, programs, arch: Arch):
        self.programs = programs            # per-core programs
        self.arch = arch
        self.lines = []
        self.indent = 0
        self._event_ids = {}
        self._buf_ids = {}
        self._tmp = 0

    # ------------------------------------------------------------- helpers

    def w(self, text=""):
        self.lines.append("    " * self.indent + text if text else "")

    def comment(self, text):
        self.w(f"// {text}")

    def _event_id(self, event, stage):
        key = (event.name, stage)
        if key not in self._event_ids:
            pair = (event.prod.kind, event.cons.kind)
            he = _HARD_EVENT.get(pair, "HardEvent::MTE2_V")
            self._event_ids[key] = (f"EVT_{event.name.upper()}_{stage}", he)
        return self._event_ids[key]

    def _local(self, view, stage, prefix="buf"):
        key = (view.name, stage)
        if key not in self._buf_ids:
            self._buf_ids[key] = f"{prefix}_{view.name}_{stage}"
        return self._buf_ids[key]

    # --------------------------------------------------------------- emit

    def generate(self) -> str:
        p0 = self.programs[0]
        self._header(p0)
        self.w(f'extern "C" __global__ __aicore__ void {p0.name}(')
        self.indent += 2
        for i, p in enumerate(p0.params):
            sep = "," if i < len(p0.params) - 1 else ""
            self.w(f"{_ASCENDC_TYPE[p.dtype]}* __restrict__ {p.name}{sep}  "
                   f"/* {p.shape} {p.dtype} */")
        self.indent -= 2
        self.w(") {")
        self.indent += 1
        if len(self.programs) == 1:
            self._body(self.programs[0], core_guard=None)
        else:
            for core, prog in enumerate(self.programs):
                self._body(prog, core_guard=core)
        self.indent -= 1
        self.w("}")
        return "\n".join(self.lines) + "\n"

    def _header(self, prog: Program):
        self.comment("Generated by CAKE-Ascend lowering - inspectable by design.")
        self.comment(f"kernel: {prog.name}   target: {prog.arch_name}   "
                     f"block_dim: {prog.block_dim}")
        self.comment("Lowering derives: UB offsets, bufferNum depths, HardEvent ids,")
        self.comment("flag pairing and loop structure from the IR declarations.")
        self.w("#include \"ascendc/kernel.h\"")
        self.w()

    # --------------------------------------------------------------- body

    def _body(self, prog: Program, core_guard):
        if core_guard is not None:
            self.w(f"if (GetBlockIdx() == {core_guard}) {{")
            self.indent += 1
        self._emit_pipeline(prog)
        self._emit_ops(prog)
        if core_guard is not None:
            self.indent -= 1
            self.w("}")
        return

    def _emit_pipeline(self, prog: Program):
        self.comment(f"---- core program: roles "
                     f"{', '.join(f'{r.name}:{r.kind}' for r in prog.roles)} ----")
        # derived event declarations
        seen = set()
        for e in prog.events:
            for s in range(e.pipeline.stages if e.pipeline else 1):
                eid, he = self._event_id(e, s)
                if eid in seen:
                    continue
                seen.add(eid)
                self.w(f"constexpr auto {eid} = {he};")
        if seen:
            self.w()
        # derived buffer init
        for view in prog.ub_views:
            bytes_ = view.slot_bytes
            bufnum = view.stages
            self.comment(f"view '{view.name}': offset {view.offset} B, "
                         f"{view.shape} x {view.dtype}, bufferNum={bufnum}")
            for s in range(view.stages):
                self.w(f"TPipe pipe_{view.name}_{s};")
                self.w(f"TBuf<TPosition::VECCALC> {self._local(view, s)};")
                self.w(f"pipe_{view.name}_{s}.InitBuffer("
                       f"{self._local(view, s)}, {bytes_});")
        for r in prog.l0c_regions:
            self.w(f"TCubeTBuf<TPosition::A1A2C1C2> l0c_{r.name}; "
                   f"/* {r.shape} fp32 accumulator, L0C */")
        self.w()

    def _emit_ops(self, prog: Program):
        # re-roll loops from markers; core_id-dependent constants already baked
        stack = []  # (marker, indent at open)
        for op in prog.ops:
            if isinstance(op, LoopMarker):
                if op.is_begin:
                    var = op.var.replace("@", "_")
                    self.w(f"for (int {var} = 0; {var} < {op.count}; ++{var}) {{")
                    self.indent += 1
                    stack.append(op)
                else:
                    self.indent -= 1
                    self.w("}")
                    if stack:
                        stack.pop()
                continue
            if isinstance(op, Gm2Ub):
                self._emit_gm2ub(op)
            elif isinstance(op, Ub2Gm):
                self._emit_ub2gm(op)
            elif isinstance(op, L0c2Ub):
                self._emit_l0c2ub(op)
            elif isinstance(op, Matmul):
                self._emit_matmul(op)
            elif isinstance(op, VBinary):
                self._emit_vbinary(op)
            elif isinstance(op, VUnary):
                self._emit_vunary(op)
            elif isinstance(op, VReduce):
                self._emit_vreduce(op)
            elif isinstance(op, VArgmin):
                self._emit_vargmin(op)
            elif isinstance(op, VTranspose):
                self._emit_vtranspose(op)
            elif isinstance(op, VBcast):
                self._emit_vbcast(op)
            elif isinstance(op, VCast):
                self._emit_vcast(op)
            elif isinstance(op, Commit):
                eid, _ = self._event_id(op.event, op.stage)
                self.w(f"SetFlag<{eid}>();  /* commit '{op.event.name}' stage {op.stage} */")
            elif isinstance(op, Wait):
                eid, _ = self._event_id(op.event, op.stage)
                self.w(f"WaitFlag<{eid}>();  /* wait '{op.event.name}' stage {op.stage} */")
            elif isinstance(op, HardBarrier):
                self.w("SyncAll();  /* hard barrier: block scope */")

    # -------------------------------------------------------- op emitters

    def _view_local(self, op_view, stage_attr):
        return self._local(op_view, getattr(op, stage_attr))

    def _emit_gm2ub(self, op: Gm2Ub):
        dst = self._local(op.dst, op.stage)
        off = ", ".join(str(o) for o in op.gm_off)
        n = shape_numel(op.dst.shape)
        self.comment(f"gm2ub {op.src.name}[{off}] -> {op.dst.name}[{op.stage}] "
                     f"({op.dst.shape})")
        self.w(f"DataCopy({dst}.template GetTensor<{_ASCENDC_TYPE[op.dst.dtype]}>(), "
               f"{op.src.name} + _offset_{op.src.name}_{abs(hash((op.src.name, op.gm_off))) % 9973}, "
               f"{n});")

    def _emit_ub2gm(self, op: Ub2Gm):
        src = self._local(op.src, op.stage)
        off = ", ".join(str(o) for o in op.gm_off)
        n = shape_numel(op.src.shape)
        self.comment(f"ub2gm {op.src.name}[{op.stage}] -> {op.dst.name}[{off}]")
        self.w(f"DataCopy({op.dst.name} + _offset_{op.dst.name}_{abs(hash((op.dst.name, op.gm_off))) % 9973}, "
               f"{src}.template GetTensor<{_ASCENDC_TYPE[op.src.dtype]}>(), {n});")

    def _emit_l0c2ub(self, op: L0c2Ub):
        dst = self._local(op.dst, op.stage)
        self.comment(f"l0c2ub {op.src.name} -> {op.dst.name}[{op.stage}] ({op.dst.shape})")
        self.w(f"CopyTensor({dst}.template GetTensor<float>(), "
               f"l0c_{op.src.name}.template GetTensor<float>(), "
               f"{shape_numel(op.src.shape)});")

    def _emit_matmul(self, op: Matmul):
        a = self._local(op.a, op.a_stage)
        b = self._local(op.b, op.b_stage)
        m, k = op.a.shape
        _, n = op.b.shape
        self.comment(f"matmul {op.a.name}[{op.a_stage}]x{op.b.name}[{op.b_stage}] "
                     f"-> {op.acc.name} ({m}x{k}x{n}, clear={op.clear})")
        self.w("{")
        self.indent += 1
        self.w("using MatmulT = Matmul<")
        self.indent += 1
        self.w(f"{_ASCENDC_TYPE[op.a.dtype]}, {_ASCENDC_TYPE[op.b.dtype]}, float,")
        self.w(f"MatmulFormat::ND, {m}, {k}, {n}, {str(op.clear).lower()}>;")
        self.indent -= 1
        self.w("MatmulT mm;")
        self.w(f"mm.SetTensorA({a}.template GetTensor<{_ASCENDC_TYPE[op.a.dtype]}>());")
        self.w(f"mm.SetTensorB({b}.template GetTensor<{_ASCENDC_TYPE[op.b.dtype]}>());")
        self.w(f"mm.SetTensorC(l0c_{op.acc.name}.template GetTensor<float>());")
        self.w("mm.Iterate();")
        self.indent -= 1
        self.w("}")

    def _tmpvar(self):
        self._tmp += 1
        return f"t{self._tmp}"

    def _emit_vbinary(self, op: VBinary):
        dst = self._local(op.dst, op.dst_stage)
        x = self._local(op.x, op.x_stage)
        n = shape_numel(op.dst.shape)
        if op.y is not None:
            y = self._local(op.y, op.y_stage)
            self.comment(f"{op.op}: {op.x.name} + {op.y.name} -> {op.dst.name}")
            self.w(f"BinaryOps<{_vop(op.op)}>({dst}, {x}, {y}, {n});")
        else:
            self.comment(f"{op.op}: {op.x.name} * {op.y_scalar} -> {op.dst.name}")
            self.w(f"BinaryOps<{_vop(op.op)}>({dst}, {x}, "
                   f"static_cast<{_ASCENDC_TYPE[op.dst.dtype]}>({op.y_scalar}), {n});")

    def _emit_vunary(self, op: VUnary):
        dst = self._local(op.dst, op.dst_stage)
        x = self._local(op.x, op.x_stage)
        n = shape_numel(op.dst.shape)
        self.comment(f"{op.op}: {op.x.name} -> {op.dst.name}")
        self.w(f"UnaryOps<{_vop(op.op)}>({dst}, {x}, {n});")

    def _emit_vreduce(self, op: VReduce):
        dst = self._local(op.dst, op.dst_stage)
        x = self._local(op.x, op.x_stage)
        r, c = op.x.shape
        self.comment(f"reduce {op.op} axis=-1: {op.x.name} ({r}x{c}) -> {op.dst.name}")
        self.w(f"Reduce<{_vop(op.op)}>({dst}, {x}, {c}, {r});")

    def _emit_vargmin(self, op: VArgmin):
        dst = self._local(op.dst, op.dst_stage)
        x = self._local(op.x, op.x_stage)
        r, c = op.x.shape
        self.comment(f"argmin axis=-1: {op.x.name} ({r}x{c}) -> {op.dst.name}")
        self.w(f"ArgMin({dst}, {x}, {c}, {r});")

    def _emit_vtranspose(self, op: VTranspose):
        dst = self._local(op.dst, op.dst_stage)
        x = self._local(op.x, op.x_stage)
        r, c = op.x.shape
        self.comment(f"transpose: {op.x.name} ({r}x{c}) -> {op.dst.name}")
        self.w(f"Transpose({dst}, {x}, {r}, {c});")

    def _emit_vbcast(self, op: VBcast):
        dst = self._local(op.dst, op.dst_stage)
        x = self._local(op.x, op.x_stage)
        r, c = op.dst.shape
        self.comment(f"bcast {op.mode}: {op.x.name} -> {op.dst.name} ({r}x{c})")
        self.w(f"Broadcast<{ 'ROW' if op.mode == 'row' else 'COL'}>({dst}, {x}, {r}, {c});")

    def _emit_vcast(self, op: VCast):
        dst = self._local(op.dst, op.dst_stage)
        x = self._local(op.x, op.x_stage)
        n = shape_numel(op.dst.shape)
        self.comment(f"cast {op.x.dtype}->{op.dst.dtype}: {op.x.name} -> {op.dst.name}")
        self.w(f"Cast<{_ASCENDC_TYPE[op.dst.dtype]}>({dst}, {x}, {n});")


_V_BINARY = {"add": "BinaryOp::ADD", "sub": "BinaryOp::SUB", "mul": "BinaryOp::MUL",
             "min": "BinaryOp::MIN", "max": "BinaryOp::MAX"}
_V_UNARY = {"neg": "UnaryOp::NEG", "abs": "UnaryOp::ABS", "sqrt": "UnaryOp::SQRT",
            "exp": "UnaryOp::EXP", "copy": "UnaryOp::MOV"}
_V_REDUCE = {"sum": "ReduceOp::SUM", "min": "ReduceOp::MIN", "max": "ReduceOp::MAX"}


def _vop(op):
    if op in _V_BINARY:
        return _V_BINARY[op]
    if op in _V_UNARY:
        return _V_UNARY[op]
    if op in _V_REDUCE:
        return _V_REDUCE[op]
    return op.upper()


def generate_ascendc(programs, arch: Arch) -> str:
    if not programs:
        raise ValueError("no programs to lower")
    return AscendCCodeGen(programs, arch).generate()
